# Generated by Django 5.1.7 on 2025-03-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_customuser_role_bankpersonnel_loancustomer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanprovider',
            name='available_funds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
