# Generated by Django 5.1.7 on 2025-03-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_approved_loanprovider_available_funds'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_duration', models.IntegerField()),
                ('max_duration', models.IntegerField()),
            ],
        ),
    ]
